name: Build + Test
on: push

jobs:
  cucumber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Install Deps
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz
          mkdir bin && tar -xvzf vale_${VALE_VERSION}_Linux_64-bit.tar.gz -C bin
          echo "./bin" >> $GITHUB_PATH
          pip install yamllint pyyaml docutils
        env:
          VALE_VERSION: 3.3.0
      - name: Features
        run: bundle exec cucumber --format progress
        env:
          CUCUMBER_PUBLISH_QUIET: true
